"""initial schema: api_keys, usage_events

Revision ID: 6c36f13cb022
Revises: 
Create Date: 2026-08-17 15:54:11.672284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c36f13cb022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_ref', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_account_ref'), 'api_keys', ['account_ref'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('account_ref', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('bytes_in', sa.Integer(), nullable=False),
    sa.Column('bytes_out', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('credits_table_version', sa.Integer(), nullable=False),
    sa.Column('external_cost_micros', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_events_account_occurred', 'usage_events', ['account_ref', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_events_account_ref'), 'usage_events', ['account_ref'], unique=False)
    op.create_index(op.f('ix_usage_events_api_key_id'), 'usage_events', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_events_occurred_at'), 'usage_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_events_request_id'), 'usage_events', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_request_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_occurred_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_api_key_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_account_ref'), table_name='usage_events')
    op.drop_index('ix_usage_events_account_occurred', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_api_keys_account_ref'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
